#!/usr/bin/perl
# mpdscrobloc - local scrobbling for MPD
use strict;
use Audio::MPD;

my $mpd = Audio::MPD->new();
my $history = "$ENV{HOME}/.mpd/mpd.history";

my $color_support = 256; # 16, 88
my $stdout = 1; # print to stdout too?

my @colors;
for(my $i=0;$i<$color_support;$i++) {
  push(@colors, "\033[38;5;$i".'m');
}

my $current = "";
while(1) {
  my $np = $mpd->current;
  my $artist = $np->artist // '';
  my $album  = $np->album  // '';
  my $title  = $np->title  // '';
  my $file   = $np->file;

  if("$current" ne "$np") {
    $current = $np;
    if($stdout) {
      printf("$colors[100]%s$colors[101] %s ($colors[102]%s)\033[0m\n",
        $artist, $title, $album);
    }
    open(my $fh, '>>', $history) or die "Can not open $history: $!";
    print $fh "\"@{[scalar(localtime)]}\",\"$artist\",\"$title\"\n";
    close $fh;
  }
  sleep 2;
}
